AK-14181 Add AWS-VPC routing options support to resource_alkira_conne…
alkiranet/terraform-provider-alkira pull request #4
Opened 2021-03-15 18:06 UTC by spikewang

…ctor_aws_vpc

Adding routing options support to resource_alkira_connector_aws_vpc. With this
commit, either vpc_cidr or vpc_subnets is needed for creating AWS-VPC connector.

+ add new var `vpc_cidr` to specify AWS-VPC CIDR.
+ Add new var `vpc_subnets` to specifcy AWS-VPC subnets.
+ Add new set `vpc_routetable` to specify AWS-VPC route tables and prefixs.

2021-03-15 18:26 UTC, spikewang commented
Now with AWS-VPC connector, we will need either `vpc_cidr` or `vpc_subnets` as part of the input. If you have older configuration, error message will be displayed during `terraform plan` or `terraform apply` to remind you this.

To use the new route table section:

```
  vpc_route_table {
    id              = "rtb-XXXX"
    prefix_list_ids = [data.alkira_policy_prefix_list.test1.id]
    options         = "ADVERTISE_CUSTOM_PREFIX"
  }
```

2021-03-15 19:16 UTC, rvichery requested changes
Couple of small things to fix for better validation.
Also I am wondering if we should use TypeList for `billing_tags`, `vpc_subnets` and `prefix_list_ids` as they are not ordered collection of items AFAIK.

2021-03-15 19:16 UTC, rvichery commented on alkira/resource_alkira_connector_aws_vpc.go
> +						"options": {
We should probably add:
```
ValidateFunc: validation.StringInSlice([]string{"ADVERTISE_DEFAULT_ROUTE", OVERRIDE_DEFAULT_ROUTE", "ADVERTISE_CUSTOM_PREFIX"}, false),
```

2021-03-15 20:29 UTC, spikewang commented on alkira/resource_alkira_connector_aws_vpc.go
> +						"options": {
Yep, about to do that.

2021-03-15 20:45 UTC, spikewang commented on alkira/helper.go
> +		return nil, fmt.Errorf("ERROR: vpc_subnets and vpc_cidr can't be specified at the same time.")
Let me check

2021-03-15 23:59 UTC, sahilthapar1234 approved these changes

2021-03-16 00:42 UTC, spikewang commented
Yep, we could, will do those changes in a separate one. Couple more changes are pending..

2021-03-16 00:44 UTC, merged